### ISSUE TITLE
Excluded the gradle-wrapper.jar

### ISSUE THREAD

**Issue by PizzaCrust** [Vrekt/Athena#13]
You ignored the gradle-wrapper.jar which makes the gradlew.bat useless
(if you don't have a previous installation of gradle)

**Comment by Vrekt** [comment]
Is it needed though? I didn't mean to include everything only the build.gradle file which you can import into pretty much any IDE

**Comment by Vrekt** [comment]
Also I'm a lazy cunt and have shit upload speed which means it takes a couple minutes to upload a few mbs

**Comment by PizzaCrust** [comment]
ill send a pull request + it's extremely convenient for cloning and building things on the fly instead of importing it into an IDE
