### ISSUE TITLE
Party invite event never fired

### ISSUE THREAD

**Issue by PizzaCrust** [Vrekt/Athena#15]
Seems like only ping event gets fired, don't really know what Fortnite did in the update

**Comment by Vrekt** [comment]
Well, first time invite the event will always get fired, all invites after that are 'pings'. You can listen to both the invite and ping event to receive invites.

**Comment by PizzaCrust** [comment]
I'm an idiot, I was listening to another event; that's why it seemed it never fired. BTW ping event doesn't have party id its always null

**Comment by Vrekt** [comment]
Ping messages don't contain a party ID because its not given in the original packet/message. You'll have to store initial invites and then go off that I guess, little scuffed.

**Comment by PizzaCrust** [comment]
What is considered first time invite, as I can't make it do it consistently

**Comment by Vrekt** [comment]
So what you have to do is, you create a new party in-game you can do this by 
1. Clicking choose gamemode
2. Going back into battle royale

This will create a new party, and you will receive the invite event and a ping.
Epic made it so you cannot send multiple invites so if you already invited the person once and they didn't join or decline then its still considered a pending invite.

I'm guessing ping is their way of getting around this, maybe they didn't want to change the back-end too much or something.

**Comment by PizzaCrust** [comment]
Your steps work but if I use an existing party and invite the user, the event doesn't get fired only the ping event. (how would i get around that) BTW why do some events get logged and some do not that's why i started the issue in the first case as it looked like everything was logged

**Comment by Vrekt** [comment]
I'm not sure what you mean by the log thing, they all should get logged if you didn't get the event then you didn't get it.

To get around the ping issue, you can get the account ID of the event and use this to get the party ID.
```
        resource.getPartyByAccountId(accountId).ifPresent(party -> {
           // do something
        });
```

**Comment by Vrekt** [comment]
^^ Let me know if that works or not, if not then I have another workaround

**Comment by PizzaCrust** [comment]
Tried that already, received a forbidden response

**Comment by Vrekt** [comment]
Alright, give me a minute or two here to try something

**Comment by PizzaCrust** [comment]
The invite event is fired on my listener but it doesn't seem to log the request or I am just overlooking it

**Comment by Vrekt** [comment]
Requests don't get logged, only if they failed and need to re-send (or there is a debug line somewhere).

To get around the ping issue you can use:
```
       resource.getInvites().forEach(invite -> {
            if(invite.sentById().equals(event.accountId())) {
                // do something
            }
       });
```

**Comment by PizzaCrust** [comment]
did that, empty list

**Comment by Vrekt** [comment]
Not sure then, I guess the invite either expired or got revoked? My testing shows the invite everytime I receive a ping.

**Comment by PizzaCrust** [comment]
That's weird, maybe i did something wrong i'll check

**Comment by leomelki** [comment]
Hey, I found a way to resolve this problem:
You need to save partyIds sent by users on their presence packets and then reuse them when you receive a ping !
The only problem I have is when I restart the bot, he don't get thhe party presence of users which are already playing the game. Is there a way to reload the roaster like before to receive party presence of everyone at once ?

**Comment by Vrekt** [comment]
I don't think that would work if their party was private?

**Comment by leomelki** [comment]
I'll try it but I think it still works, putting your party in private doesn't disable people to see your presence status

**Comment by Vrekt** [comment]
Well no, but it won't give you the party ID.

**Comment by Vrekt** [comment]
Also, I've never had a problem with getting party IDs, I would always get the initial invite which has the party ID and would just store it from there. So I can't help all that much since I don't have experience with this situation

**Comment by leomelki** [comment]
Ok I just found that when you're in private, it sends an invitation and when the user is in friend or public mode, it just sends a ping.
